branches:
  only:
    - master
language: erlang
otp_release:
  - 18.3
  - 18.0
  - 17.4
  - 17.0
env:
  - LLVM_VERSION=3.5.2
  - LLVM_VERSION=3.6.2
  - LLVM_VERSION=3.7.1
  - LLVM_VERSION=3.8.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
script: "make all rebar_regression"
sudo: false
before_cache:
  - ./travis/store_plt.sh
before_script:
  - ./travis/install_deps.sh
  - export LLVM_DIR=$PWD/cache/clang+llvm-$LLVM_VERSION
  - export PATH=$LLVM_DIR/bin:$PATH
  - export LD_LIBRARY_PATH=$LLVM_DIR/lib
  - export CPATH=/usr/lib/gcc/x86_64-linux-gnu/4.9/include
  - export NIFTY_ROOT=$PWD
after_failure:
  - ./travis/after_failure.sh
cache:
  directories:
    - cache
