branches:
  only:
    - master
language: erlang
otp_release:
  - 18.3
  - 18.0
  - 17.4
  - 17.0
env:
  - NIFTY_LLVM_VERSION=3.4 LD_LIBRARY_PATH=/usr/lib/llvm-3.4/lib
  - NIFTY_LLVM_VERSION=3.6 CPATH=/usr/lib/gcc/x86_64-linux-gnu/4.6/include:/usr/lib/llvm-3.6/include LD_LIBRARY_PATH=/usr/lib/llvm-3.6/lib
  - NIFTY_LLVM_VERSION=3.7 CPATH=/usr/lib/gcc/x86_64-linux-gnu/4.6/include:/usr/lib/llvm-3.7/include LD_LIBRARY_PATH=/usr/lib/llvm-3.7/lib
  - NIFTY_LLVM_VERSION=3.8 CPATH=/usr/lib/gcc/x86_64-linux-gnu/4.6/include:/usr/lib/llvm-3.8/include LD_LIBRARY_PATH=/usr/lib/llvm-3.8/lib
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
    packages:
      - llvm-3.4
      - llvm-3.6
      - llvm-3.7
      - llvm-3.8
      - libclang1-3.4
      - libclang1-3.6
      - libclang1-3.7
      - libclang1-3.8
      - libclang-3.4-dev
      - libclang-3.6-dev
      - libclang-3.7-dev
      - libclang-3.8-dev
script: "echo `llvm-config-3.4 --ldflags`; make all rebar_regression"
sudo: false
